### ISSUE TITLE
enabledKey & enabledPath  missing in 97saml20-idp-hosted.php

### ISSUE THREAD

**Issue by ofriedri** [NetKnights-GmbH/privacyidea-ucs-saml#21]
The two SAML attributes `enabledKey` & `enabledPath` are initialized in the template `97saml20-idp-hosted.php` but are missing in the final print statement. Therefore, the authproc filter is not working properly!

**Comment by nilsbehlen** [comment]
Hi, you mean this print
https://github.com/NetKnights-GmbH/privacyidea-ucs-saml/blob/39913aa7ea4fe99cc9e9c66223242ddfa3fb6c28/conffiles-v1.9/etc/simplesamlphp/metadata/97saml20-idp-hosted.php#L37 ?

**Comment by ofriedri** [comment]
Yes, it's this. The variables are initialized in L10 & L11, but missing in the print function. Easy fix :-)

**Comment by ofriedri** [comment]
https://github.com/NetKnights-GmbH/privacyidea-ucs-saml/pull/23

**Comment by nilsbehlen** [comment]
Easy if you know what you are doing ;) thanks for the fix!
