### ISSUE TITLE
Template file97saml20-idp-hosted.php doesn't refer all UCR variables

### ISSUE THREAD

**Issue by ofriedri** [NetKnights-GmbH/privacyidea-ucs-saml#22]
Not all UCR variables are registered in the file `debian/privacyidea-ucs-saml.univention-config-registry`, which leads to manual interaction when updating one of the mentioned variables (effectively: `ucr commit /etc/simplesamlphp/metadata/saml20-idp-hosted.php`)
```
E:0004-29: conffiles/etc/simplesamlphp/metadata/97saml20-idp-hosted.php: template file contains variables that are not registered in multifile or subfile entry:
	- hostname
	- domainname
	- privacyidea/saml/url
	- privacyidea/saml/verifyhost
	- privacyidea/saml/verifypeer
	- privacyidea/saml/enabledPath
	- privacyidea/saml/enabledKey
	- privacyidea/saml/excludeEntityIDs
	- privacyidea/saml/includeAttributes
	- privacyidea/saml/setPath
	- privacyidea/saml/setKey
	- privacyidea/saml/excludeClientIPs
	- privacyidea/saml/realm
	- privacyidea/saml/uidkey
```

**Comment by nilsbehlen** [comment]
So they are missing in this section?
https://github.com/NetKnights-GmbH/privacyidea-ucs-saml/blob/39913aa7ea4fe99cc9e9c66223242ddfa3fb6c28/debian/privacyidea-ucs-saml.univention-config-registry#L15

**Comment by ofriedri** [comment]
Yes they are, the file should refer to all UCR variables used by the template declared in the `Multifile`

**Comment by ofriedri** [comment]
https://github.com/NetKnights-GmbH/privacyidea-ucs-saml/pull/24
